application: lizardanalyzer
version: 1
runtime: python36
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: index.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lizard
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
#- ^(.*/)?.*lib/local/.*
